server:
  port: 8080
  servlet:
    context-path: /scheduler

spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /

app:
  read-only: false
  rabbit:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
